[project]
name="pulse_api"
description="API para plataforma Pulse de Zembia"
version="0.1.3"
authors=[
  {name = "Zembia SpA", email = "desarrollo@zembia.cl"}
]
dependencies = [
  "requests>=2.25.1"
]
